db_path       : ./database.db
pid           :
v_default     :
port          : 2222
manual_mode   : true
timeout       : 2
seek_timeout  : 30
wait_before_automatic_request: 3
quorum        :
nodes:
  - http://35.222.255.1:2222
  - http://35.222.232.57:2222
  - http://35.222.123.35:2222
  - http://46.101.141.5:2222
  - http://142.93.165.135:2222
controller_port: 2221