db_path       : ./database.db
pid           : 2222
v_default     : arch@2222
port          : 2222
manual_mode   : true
timeout       : 2
seek_timeout  : 30
quorum        : 
nodes:
  - http://127.0.0.1:2222
  - http://127.0.0.1:3333
  - http://127.0.0.1:4444
  - http://127.0.0.1:5555
controller_port: 2221